Map<int, String> migrationScripts = {
  1: '''CREATE TABLE IF NOT EXISTS `profile` (
        `userId` TEXT, 
        `nik` TEXT, 
        `username` TEXT, 
        `password` TEXT, 
        `typeuserCode` TEXT, 
        `typeuserName` TEXT, 
        `code` TEXT, 
        `name` TEXT, 
        `address` TEXT, 
        `tempatLahir` TEXT, 
        `tglLahir` TEXT, 
        `tglMasuk` TEXT, 
        `email` TEXT, 
        `phone1` TEXT, 
        `phone2` TEXT, 
        `photo` TEXT, 
        `photoKtp` TEXT, 
        `noKtp` TEXT, 
        `typeuserId` TEXT, 
        `divisiCode` TEXT, 
        `jabatanCode` TEXT, 
        `deviceId` TEXT, 
        `deviceBrand` TEXT, 
        `deviceType` TEXT, 
        `firebaseId` TEXT, 
        `costCenterCode` TEXT, 
        `lokasi` TEXT, 
        `organizationLevel` TEXT, 
        PRIMARY KEY (`userId`))''',
  2: '''ALTER TABLE `profile` ADD `status` INTEGER''',
  3: '''ALTER TABLE `profile` ADD `statusKirim` INTEGER''',
  4: '''ALTER TABLE `profile` ADD `createdAt` TEXT''',
  5: '''ALTER TABLE `profile` ADD `updatedAt` TEXT''',
};